name: Development Deployment

on:
  push:
    branches:
      - dev
jobs:
  "Continuous-Integration":
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install --save-dev husky
      - name: Linting
        run: npm run lint
      - name: Formatting check
        run: npm run format
      - name: Build Next.js
        run: npm run build

  "Deploy-Dev-Server":
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_DEPLOY_IP }}
          username: ${{ secrets.DEV_DEPLOY_USERNAME }}
          key: ${{ secrets.DEV_DEPLOY_SSH_KEY }}
          script: |
            cd app/twelve-tea-one/website
            git pull origin dev
            npm install
            npm run build
            pm2 restart 12t1-web

          
  