name: Continuous Integration

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install --save-dev husky
      - name: Linting
        run: npm run lint
      - name: Formatting check
        run: npm run format
      - name: Build Next.js
        run: npm run build